MIN_COOCKING_TIME = 1
MAX_COOCKING_TIME = 720
MIN_INGREDIENT_AMOUNT = 1
MAX_INGREDIENT_AMOUNT = 5000

MAX_INGREDIENT_NAME_LENGTH = 128
MAX_RECIPE_NAME_LENGTH = 256
MAX_INGREDIENT_UNIT_LENGTH = 64
MAX_USER_NAME_LENGTH = 150
MAX_EMAIL_LENGTH = 254
MAX_SHORT_HASH_LENGTH = 8
